2022-06-03 15:55:26,286 Serving on http://0.0.0.0:5000
2022-06-03 15:56:34,639 Exception while serving /survey
Traceback (most recent call last):
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\waitress\channel.py", line 426, in service
    task.service()
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\a\Desktop\surveyapp\survey\backend\src\routes\survey.py", line 57, in handle_survey
    survey_id_for_action = int(request.args.get("surveyId"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2022-06-03 15:56:56,854 Exception while serving /survey
Traceback (most recent call last):
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\waitress\channel.py", line 426, in service
    task.service()
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\a\Documents\Projects\pyvenvs\bhaiko_venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\a\Desktop\surveyapp\survey\backend\src\routes\survey.py", line 57, in handle_survey
    survey_id_for_action = int(request.args.get("surveyId"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2022-06-03 15:57:58,058 Survey with name test8 created successfully.
